import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import SessionWrapper from './providers/SessionProvider';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Quick Cart',
  description: 'Generated by Quick Cart eCommerce',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionWrapper>{children}</SessionWrapper>

        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
